version: '3.4'
services:
  frontend:
    container_name: 'frontend'
    build: ./frontend
    ports:
      - "80:80"
    environment:
      - MYSQL_SERVER=backend
      - MYSQL_USER=root
    links:
      - backend

  backend:
    container_name: 'backend'
    build: ./backend
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASS=
